import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import Head from "next/head";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({weight: ['400', '900', '700', '500', '200', '300'], subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${poppins.className} flex bg-[#090909]`}>

      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            // enableSystem
            disableTransitionOnChange
          >
            <SideBar></SideBar>
            {children}
          </ThemeProvider></body>
    </html>
  );
}
